spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/daweb_db
    username: admin
    password: adminpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      encoding: UTF-8

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true